version: "3.9"

services:
  mysqldb:
    image: mysql:8    
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=drones_db
      - MYSQL_ROOT_PASSWORD=r00t
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp@ssw0rd
    volumes:
      - drones:/var/lib/mysql

  app:
    image: drone-app
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - USER_DB_URL=jdbc:mysql://mysqldb:3306/drones_db?createDatabaseIfNotExist=true
      - USER_DB_USERNAME=dbuser
      - USER_DB_PASSWORD=dbp@ssw0rd
    depends_on:
      - mysqldb
    volumes:
      - drones:/usr/app/app
      - .m2:/root/.m2
  
volumes:
  drones: